### ISSUE TITLE
Always Failing HostAnchor

### ISSUE THREAD

**Issue by ramrcram** [google-ar/arcore-ios-sdk#11]
First of all thanks for the great arcore sdk. 

When I am trying the sample project which provided by google-ar, I am not able to host the anchor.
Tapping on the Plane surface the "ANDY" has been placing, But it trigged didFailToHostAnchor delegate method. Below are the steps which i have done. 
1. Downloaded sample app 
2. Added "GoogleService-Info" (tapping on the host, New room has been created).
3. Added new API key
4. Enabled ARCore Cloud Anchor API in console.cloud.google.com. 

Please let me know if am missing anything to make it work. I really so excited to looking forward to arcore sdk.

Thanks in advance.

**Comment by Jacquelinett** [comment]
Did you set up Firebase real-time database?

**Comment by ramrcram** [comment]
@Jacquelinett, Thanks for the reply. Yes, I do set up the firebase real-time database. 
Rooms object has been created in firebase. ( Attached screenshot)

<img width="219" alt="screen shot 2018-07-22 at 21 41 14" src="https://user-images.githubusercontent.com/1559744/43049469-ac6b6292-8df8-11e8-842e-767eb177545b.png">

**Comment by sammcd** [comment]
Thanks for checking out the sample project, and sorry you are running into this issue.

It might be worth modifying the sample app's `hostCloudAnchor:error:` call, to print out the error. Let me know if it gives you anything interesting there.

If it doesn't, the app's `- (void)session:(GARSession *)session didFailToHostAnchor:(GARAnchor *)anchor {` method you could print out the anchor's cloudState property. Between these two things we should be able to find out exactly what is going wrong.

Thanks!

**Comment by ramrcram** [comment]
Thanks for the suggestions. Below is the debugging details.
`hostCloudAnchor:error:` given error as nil. 
`- (void)session:(GARSession *)session didFailToHostAnchor:(GARAnchor *)anchor` cloud state property is `GARCloudAnchorStateErrorInternal`. 

Thanks!

**Comment by sammcd** [comment]
Sorry this is a pretty tough one to debug on our end. Would you mind giving us your GCP project number (https://cloud.google.com/resource-manager/docs/creating-managing-projects#identifying_projects)?

This will help us find a little more info on exactly what is going wrong.

Thanks a lot for your patience!

**Comment by sammcd** [comment]
We've looked into this a little on our side.

My best guess is that our API hasn't seen enough ARFrames with a good tracking state to host the anchor.

My best suggestion to mitigate this would be to:
1) Launch the app
2) Make sure you move the app around enough that it is able to locate a plane. We show these in the app in a blue color.
3) Attempt to host the anchor.

My assumption is that step 2) was the missing step. Let me know if this helps. If it doesn't I can look into other reasons this could be happening.

Thanks again for your patience!

**Comment by msekast** [comment]
I'm seeing an internal error as well, but I'm on xcode 10.0 beta 4/iOS 12 beta.

**Comment by ramrcram** [comment]
@msekast I'm too on Xcode 10.0 beta 4/iOS 12 beta.
@sammcd, No luck :( I have tried your suggestion but still am getting an internal error.

**Comment by sammcd** [comment]
Thanks for the additional info! I apologize for not asking sooner if you are on the current iOS beta.

We have a bug that is fixed in the next release (1.4) that causes this issue on iOS 12. We should be launching this fix within a week. I will update this thread when I release that version. If you would like to continue testing it might be helpful to test on an iOS 11 device until we get this fix out.

**Comment by ramrcram** [comment]
Cool thanks @sammcd.  My bad I should have mention iOS version in the first place. :(. 
Thanks for taking care, Waiting for the new release. 👍

**Comment by sammcd** [comment]
We recently released 1.4.0 which includes this fix. Update your podfile to 1.4.0 and run `pod install --repo-update`. This should solve your issue. If it doesn't, or if you run into anything else please let me know!

**Comment by ramrcram** [comment]
👍
