### ISSUE TITLE
ARCore and Firebase Firestore issue

### ISSUE THREAD

**Issue by teamplanimal** [google-ar/arcore-ios-sdk#12]
Installing ARCore and Firebase via Cocoapods, I'm able to include a number of Firebase services (Core, Database, and Auth, for example, work fine for me) but the Firebase Firestore SDK results in 13 duplicate symbols for architecture arm64 (around names like 'GAPIHttp...' and 'RPCStatus...').

For example:

`duplicate symbol _OBJC_METACLASS_$_GAPIHttpRule in:
    /Users/christopher/Library/Developer/Xcode/DerivedData/...(omitted).../Build/Products/Debug-iphoneos/FirebaseFirestore/libFirebaseFirestore.a(HTTP.pbobjc.o)
    /Users/christopher/Developer/...(omitted).../ios/Pods/ARCore/Frameworks/ARCore.framework/ARCore(HTTP.pbobjc_b86031752773b66b1b7d14a3f41c5d52.o)
`

I initially thought perhaps it could be related to https://github.com/google-ar/arcore-unity-sdk/issues/305 but I just checked and I'm able to add Firebase Messaging without issue-- for me the issue appears to be specific to Firebase Firestore.

**Comment by sammcd** [comment]
Hello,

Thank you very much for reporting this issue, and I'm sorry you ran into it. I am able to reproduce this on my end and I've opened up a bug in our internal system so we can fix it.

Thanks again!

**Comment by teamplanimal** [comment]
Thanks, appreciate hearing back so quickly.

**Comment by sammcd** [comment]
Just wanted to update this to let you know that the fix for this issue will be in the next release of ARCore.

**Comment by sammcd** [comment]
1.5 was released today with a fix for this bug.

Thanks again for reporting it!
