### ISSUE TITLE
Crash on iPhoneXS and XSMax

### ISSUE THREAD

**Issue by kboy-silvergym** [google-ar/arcore-ios-sdk#15]
# About

When I code like this, the error occurs and crashes only built on iPhoneXS and XSMax.

```swift
do {
    gSession = try GARSession(apiKey: AppConst.apiKey, bundleIdentifier: nil)
 } catch {
    print(error.localizedDescription)
 }
```

The error is below.

```
The operation couldn’t be completed. (GARSession error -1.)
```

It seems that iPhoneXS and XSMax are not available so far.
Please fix it!

# Environment
- Xcode10.0, Swift4.2
- iPhoneXS(and XSMax), iOS12
- ARCore 1.5.0 via cocoapods

Thanks.

**Comment by sammcd** [comment]
Hello Kei,

I'm very sorry you are running into this issue.

These devices are not currently supported by ARCore iOS. You can see the list here: https://developers.google.com/ar/discover/supported-devices#ios.

We hope to fix this issue soon, and I will post updates here.

**Comment by sammcd** [comment]
Hello Kei,

As of today, you should be able to use iPhone XS and XS Max with ARCore iOS. 

Please make sure when you try again that the phone has an internet connection, and if it fails on your first try, please try again.

**Comment by kboy-silvergym** [comment]
@sammcd 
Thanks!
At the first try, `GARSession error -1.` showed again. But at the second try, It could have succeeded!

So I have a more question.
Does it always fail at first try? If so, I want it to be fixed to be able to succeed even in the first try.

**Comment by sammcd** [comment]
Currently it will fail if it does not have support for that device. When you attempted and it failed for the first time, it was probably downloading necessary information for that device. 

Thanks for the feedback about this first failure not being ideal. I will bring this to the team. This sort of feedback is very important for how we prioritize features.

Thanks!

**Comment by kboy-silvergym** [comment]
Understood 👍 
I'm looking forward to ARCore will become better and better.
