### ISSUE TITLE
ErrorNotSupportedByConfiguration

### ISSUE THREAD

**Issue by guardfromua** [google-ar/arcore-ios-sdk#18]
Hello! Using Unity for Android build.
Facing **ErrorNotSupportedByConfiguration** all the time while I am trying to host in an application.

Can you give me advice(or rephrase) what is typical errors on that one, because I can't understand in the current description (The request is not supported by the current configuration.).

Probably you have some typical use cases, when this error occurs...

**Comment by sammcd** [comment]
Hey,

First, Apologies for the very late response.

Second I think the people watching the Unity sdk issues might be a little more prepared to answer this question. Feel free to reach out them here: https://github.com/google-ar/arcore-unity-sdk
