### ISSUE TITLE
Hosting dataset processing failed

### ISSUE THREAD

**Issue by alvAro365** [google-ar/arcore-ios-sdk#22]
I'm getting following error since few days back when trying to host an anchor: AR_CLOUD_ANCHOR_STATE_ERROR_HOSTING_DATASET_PROCESSING_FAILED.

I have tried ARCore versions 1.8.0 and 1.10.0.

Do you have any idea what may cause this error?

**Comment by GUIEEN** [comment]
I tested with iPhone XR & iPhone 6S plus with same environment. 
On the iPhone XR, host fails with `ErrorHostingDatasetProcessingFailed`
but on the iPhone 6S plus, host success.

I really don't know what is the reason of this error.

**Comment by jrullman** [comment]
This was a server issue - a fix has been rolled out.

**Comment by sammcd** [comment]
As John said this should be fixed now. Please let us know if you continue to see the problem.

**Comment by FaruNuriSonmez** [comment]
Problem Continues. @sammcd 

Finished Hosting:
ErrorHostingDatasetProcessingFailed.

**Comment by FaruNuriSonmez** [comment]
> 
> 
> I'm getting following error since few days back when trying to host an anchor: AR_CLOUD_ANCHOR_STATE_ERROR_HOSTING_DATASET_PROCESSING_FAILED.
> 
> I have tried ARCore versions 1.8.0 and 1.10.0.
> 
> Do you have any idea what may cause this error?

Can you help with the problem solution? @alvAro365

**Comment by dilmerv** [comment]
Same here started today

**Comment by jrullman** [comment]
Can you try using the most recent version of the SDK, 1.20? We will soon be removing support on the server side for versions < 1.12.

**Comment by dilmerv** [comment]
Actually I got it to work after deleting my previous API Key and then generating it with AR Cloud Anchor service enabled, thanks for following up. Now I am trying to get the resolve to work by looking at your persistence anchors example.

Thanks

**Comment by FaruNuriSonmez** [comment]
> 
> 
> Actually I got it to work after deleting my previous API Key and then generating it with AR Cloud Anchor service enabled, thanks for following up. Now I am trying to get the resolve to work by looking at your persistence anchors example.
> 
> Thanks

continues the same error

**Comment by jrullman** [comment]
Which version of the SDK are you using? Are you seeing this happen with our sample app?

**Comment by FaruNuriSonmez** [comment]
> 
> 
> Which version of the SDK are you using? Are you seeing this happen with our sample app?

I am using the Cloud Anchor Example sample application, I'm using SDK 1.20 and my device is iphone 8 plus - iOS 14.2

**Comment by jrullman** [comment]
Please read about the process for hosting an anchor: https://developers.google.com/ar/develop/ios/cloud-anchors/overview#how-hosted.

In particular, you need to move around to see the area from different angles before hosting. If you stay in one place you are likely to get this error.
