### ISSUE TITLE
ErrorInvalidArgument: Could not create a cross platform ARCore session

### ISSUE THREAD

**Issue by JonasLecking** [google-ar/arcore-ios-sdk#23]
Hi! I have been assigned the task to convert a Unity project that builds upon ARCore from Android, where it works properly, to iOS. Unfortunately, I am running into some errors that, after scouring the web for a few hours, I still fail to find any solution on. The currently biggest problem is, that every time the iPhone should access the camera to detect a playing plane, there is only a white screen.
Every time the app should open the plane detection dialog, this error occurs (in the Xcode console):

```
Unloading 5 Unused Serialized files (Serialized files now loaded: 0)
WARNING: Shader Unsupported: 'ARCore/ARBackground' - Pass '' has no vertex shader
Shader 'Galactic Sudios/Ultra Emissive Particles': fallback shader 'ParticleAdditive' not found
WARNING: Shader Unsupported: 'ProBuilder/Standard Vertex Color' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'Custom/LightOnly' - Pass 'Meta' has no vertex shader
WARNING: Shader Unsupported: 'StandardGlow' - Pass 'META' has no vertex shader
WARNING: Shader Unsupported: 'StandardGlow' - Pass 'META' has no vertex shader
UnloadTime: 5.943625 ms
Could not create a cross platform ARCore session (ErrorInvalidArgument).
GoogleARCoreInternal.ARCoreIOSLifecycleManager:CreateSession(ARCoreSession)
 
(Filename: ./Runtime/Export/Debug.bindings.h Line: 45)

System memory in use before: 94.8 MB.
System memory in use after: 32.5 MB.

Unloading 871 unused Assets to reduce memory usage. Loaded Objects now: 2472.
Total: 6.682792 ms (FindLiveObjects: 0.568333 ms CreateObjectMapping: 0.087750 ms MarkObjects: 1.347167 ms  DeleteObjects: 4.678583 ms)

```

I believe the warnings and the memory information are not relevant to the error; it seems to be rather this line `Could not create a cross platform ARCore session (ErrorInvalidArgument).
` that appears to be problematic. Yet, I cannot find any information on it in the docs, ARCore's source code or the web. Does anybody have any idea where this could derive from?

I'm using an iPhone X with iOS 12.x, Xcode 10 and Unity 2018.3.6f1 Personal. ARCore is - I would dare to say due to the Android version working properly - installed correctly, the ARKit plugin is in the Asset folder as well and iOS support enabled.

**Comment by ojonyan** [comment]
nice

**Comment by chris-o3h** [comment]
@JonasLecking were you able to resolve this? I've bumped into the same issue right now following the [Quickstart for IOS](https://developers.google.com/ar/develop/unity/quickstart-ios) in the ARCore documentation from Google.

I'm wondering if this is even relevant anymore seeing as Unity has marked the Unity-ARKit-Plugin as deprecated and therefore everyone should be using ARFoundation directly in Unity.

**Comment by JonasLecking** [comment]
Hey Chris,

No I was not able to resolve it; I didn’t put much effort into it though, the app was either way mostly targeted at Android and converting it to iOS was more like exploring the potential of Unity. But I guess you’re right, ARFoundation seems to be a better option now.

**Comment by lijualivenow** [comment]
Same issue

**Comment by dorcatty** [comment]
same issue here with Uniy3D 2019 and ARCore 1.17. Please fix this issue

**Comment by jrullman** [comment]
The ARCore SDK for Unity has been deprecated in favor of the ARCore Extensions for AR Foundation.
