### ISSUE TITLE
3D- Model is not rendering

### ISSUE THREAD

**Issue by saurabh1939** [google-ar/arcore-ios-sdk#25]
In-build fox_face.scn is working fine for me.
Now we have created some 3d models in Blender & export them in both .dae OR .obj formats. From xcode I converted these models in scn but when i try to render my scn models, its not rendering on face.
Same scn model is working fine with ARKIT but not working with ARCORE

**Comment by bzok2** [comment]
I have the same issue :(, have you find a solution ? Other than go the Arkit ?

**Comment by rsfuller** [comment]
The assets may be rotated backwards (and thus not rendered if isDoubleSided is not set). 

In that case you would need to either export the assets with the expected rotation, or apply a rotation on the root scene node.

[Augmented Faces: Importing assets](https://developers.google.com/ar/develop/ios/augmented-faces/developer-guide#import_your_own_assets_into_xcode)
