### ISSUE TITLE
Build framework with ENABLE_BITCODE = true

### ISSUE THREAD

**Issue by marko012** [google-ar/arcore-ios-sdk#26]
Can you please rebuild framework ARCore/AugmentedFaces with ENABLE_BITCODE = true. We will be very appreciate, because It would keep our project with enabled bitcode and smaller size.
Thank you very much,
Marko

**Comment by rsfuller** [comment]
Bitcode support is expected to come out in the next release (1.17.0).

**Comment by rsfuller** [comment]
Bitcode is supported on Augmented Faces as of 1.17.0
