### ISSUE TITLE
Light Estimation on Augmented Face Mesh

### ISSUE THREAD

**Issue by tenback** [google-ar/arcore-ios-sdk#36]
Is there any way or tricks to support light estimation on the augmented face mesh for the front facing camera on non true-depth iOS devices?

I use the ARCore sdk to project some facial additions to the users face for iOS devices without the true-depth sensor.
But when the lighting is different on the users face (let's say the light source is coming from 1 side) the preview doesn't look that realistic, because the texture is even lighted while the users face is not.

Does anyone know how to solve this, or is there any change that this will be added to this arcore-ios-sdk without having to switch to Unity.

Thanks

**Comment by jrullman** [comment]
AugmentedFaces doesn't do lighting estimation for you, just face tracking. One possibility is you could use ARKit's lighting estimation API in conjunction with a faces session.
