### ISSUE TITLE
The release version on the App Store will freeze when running

### ISSUE THREAD

**Issue by tc1993** [google-ar/arcore-ios-sdk#37]
The release version on the App Store will freeze when running， but there is no problem in debug mode. I am using version 1.18.0。which is limited to certain models, such as iPhone11 with iOS 14.1。I don’t know how to reproduce this problem in dubug mode, so there is no way to solve it

**Comment by rsfuller** [comment]
Thanks for the report.

1). Which subspec are you using (Augmented Faces or Cloud Anchors)?

2). Can you try reproducing locally with a release configuration in Xcode (e.g. [instructions](https://pinkstone.co.uk/deploying-your-app-from-xcode-to-a-device-with-release-build-configuration/)). 

3). Can you explain what it means that the app is freezing (crashes / camera view freezes / other)?

**Comment by jrullman** [comment]
Closing as there has been no update in nearly a year.
