### ISSUE TITLE
ARRecordingManager and ARPlaybackManager Missing in iOS

### ISSUE THREAD

**Issue by hardikitservices** [google-ar/arcore-ios-sdk#41]
In Android and Unity ARKit, provided recording and playback api. 

How to recording and playback in iOS SDK.

**Comment by jrullman** [comment]
Yes, we do not provide these APIs on iOS, and do not plan to in the future.

**Comment by saurabh1939** [comment]
@hardikitservices You can customise & directly pass video feed instead of live feed. 
Play video on player and pass feeds using **faceSession?.update** method.
