### ISSUE TITLE
GARSession issue, when used with Swift language

### ISSUE THREAD

**Issue by Nikilesh-Streem** [google-ar/arcore-ios-sdk#42]
Hey Guys,
I have a problem initializing a GARSession, I have my APIkey stored in a string variable and passing it to the GARSession

var apiKeyString = "somecharactersAndnumbers"

override func viewDidLoad() {
        super.viewDidLoad()

        // Set the view's delegate
        sceneView.delegate = self
        
        // Show statistics such as fps and timing information
        sceneView.showsStatistics = true
       
        gSession = try! GARSession(apiKey: apiKeyString, bundleIdentifier: nil). //// creates error here
        
        // Create a new scene
        let scene = SCNScene(named: "art.scnassets/ship.scn")!
        
        // Set the scene to the view
        sceneView.scene = scene
    }

My environment and build settings: IOS 13.5, Ipad or any Iphone, ARCore V 1.4.0, Firebase V 7.0. My build succeeds everytime, but it fails with an exception when ever it tries to start a GARSession and throws out the below error. 

**"Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=GARSession Code=-1 "(null)":"**

Also, i have verified my APIKey and fire base setup working with objective C samples ARCore has provided. Did anyone face this issue?

**Comment by Nikilesh-Streem** [comment]
Additional details to my error, Error Domain = GARSession Code = -1 "(null)" is caused due to Device not compatible issue. I see the error code '-1' indicates that error in the file GARSession.h file.
The device that I am trying to work this out is "Ipad Pro 11.1 (2nd generation)" and I see the device listed on "ARCore Supported Devices" webpage [here](https://developers.google.com/ar/discover/supported-devices)
To eliminate options, i have updated my Xcode and Ipad as well, and they both are on 12.4 and IOS 14.4. 
Can anyone from the ARCore team help?

**Comment by jrullman** [comment]
Try using the latest version of ARCore (currently 1.26.0). Since 1.12, all ARKit-compatible devices are supported whether or not they were at the time the SDK version was released.
