### ISSUE TITLE
Can't create a working Swift Framework that has ARCore as a dependency

### ISSUE THREAD

**Issue by Cloov** [google-ar/arcore-ios-sdk#43]
I'm looking to create a framework that uses ARCore/AugmentedFaces; let's call this *ARCoreConsumer*. I'm looking to import that framework into another project, called *ARCoreConsumerTester*.

ARCore needs to be added as a dependency in the framework target, because that's where my ARCore usage actually is.

The project that consumes my framework doesn't explicitly use anything from ARCore, but when I build the project, I get a build error that points to the *import ARCoreConsumer* line (see attached image), so I've added ARCore via Cocoapods in the tester project too.

![Screenshot 2021-03-03 at 15 36 23](https://user-images.githubusercontent.com/339603/109836892-879c9500-7c3c-11eb-95f5-405e7f8d46be.png).

Once I've added ARCore in my custom-framework-consuming project, the project builds and runs, but I get an error on startup:

`F0303 16:22:58.568151       1 registration.h:174] Function with name CallbackPacketCalculator already registered.`

When I google this, I'm led to think it's related to this file in MediaPipe, but I'm not sure: [registration.h](https://github.com/google/mediapipe/blob/master/mediapipe/framework/deps/registration.h).

I've attached a test project demonstrating the issue.

[TestProject.zip](https://github.com/google-ar/arcore-ios-sdk/files/6077433/TestProject.zip)

The [full Xcode console log](https://github.com/google-ar/arcore-ios-sdk/files/6084222/full_xcode_console_log.txt) shows that a number of classes are "implemented in both", i.e. presumably both targets that import ARCore. This seems like it could be linked, although I've seen this in past projects of mine with other frameworks, and the presence of those implemented-twice warnings doesn't always mean there's an issue.

Can anyone help with this? Is there any guidance as to whether ARCore/Augmented faces _can_ be utilised in a Swift framework in this way?

Thanks

**Comment by jrullman** [comment]
The problem is "use_frameworks!" in your Podfile. This forces the app to build each pod as a separate dynamic framework, which is not only less efficient for app load time but also incompatible with a closed-source pod like ARCore.
