### ISSUE TITLE
Not able to use Android existence code to build in IOS

### ISSUE THREAD

**Issue by BijayanBhattarai** [google-ar/arcore-ios-sdk#44]
Assets/GoogleARCore/Examples/CloudAnchors/Scripts/ARKitHelper.cs(28,55): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

Assets/GoogleARCore/Examples/CloudAnchors/Scripts/ARKitHelper.cs(27,26): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

Assets/GoogleARCore/Examples/CloudAnchors/Scripts/AnchorController.cs(28,26): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/Utility/ARCoreiOSHelper.cs(28,26): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/Utility/IARCoreiOSHelper.cs(24,26): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

Assets/GoogleARCore/Examples/CloudAnchors/Scripts/ARKitHelper.cs(39,22): error CS0246: The type or namespace name 'ARHitTestResult' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/XPSession.cs(28,26): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/XPSession.cs(60,13): error CS0246: The type or namespace name 'UnityARUserAnchorComponent' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/XPSession.cs(151,13): error CS0246: The type or namespace name 'UnityARUserAnchorComponent' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/Utility/IARCoreiOSHelper.cs(31,39): error CS0246: The type or namespace name 'UnityARSessionNativeInterface' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/Utility/IARCoreiOSHelper.cs(32,41): error CS0246: The type or namespace name 'UnityARSessionNativeInterface' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/Utility/ARCoreiOSHelper.cs(58,13): error CS0246: The type or namespace name 'UnityARSessionNativeInterface' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/Utility/ARCoreiOSHelper.cs(64,13): error CS0246: The type or namespace name 'UnityARSessionNativeInterface' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/Examples/PersistentCloudAnchors/Scripts/ARViewManager.cs(31,26): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

Assets/GoogleARCore/Examples/PersistentCloudAnchors/Scripts/ARViewManager.cs(735,33): error CS0246: The type or namespace name 'ARPlaneAnchor' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/Examples/PersistentCloudAnchors/Scripts/ARViewManager.cs(740,36): error CS0246: The type or namespace name 'ARPlaneAnchor' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/Examples/PersistentCloudAnchors/Scripts/ARViewManager.cs(745,46): error CS0246: The type or namespace name 'ARHitTestResult' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/Examples/PersistentCloudAnchors/Scripts/ARViewManager.cs(155,22): error CS0246: The type or namespace name 'ARHitTestResult' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/Examples/PersistentCloudAnchors/Scripts/ARViewManager.cs(156,36): error CS0246: The type or namespace name 'ARPlaneAnchorAlignment' could not be found (are you missing a using directive or an assembly reference?)

Assets/GoogleARCore/SDK/Scripts/Managers/ARCoreIOSLifecycleManager.cs(186,58): error CS0234: The type or namespace name 'iOS' does not exist in the namespace 'UnityEngine.XR' (are you missing an assembly reference?)

**Comment by jrullman** [comment]
The legacy ARCore Unity SDK has been deprecated for a long time. Please use the ARCore Extensions for AR Foundation instead.
