### ISSUE TITLE
How to get 468 face landmarks using ARCore

### ISSUE THREAD

**Issue by KotadiyaHiral** [google-ar/arcore-ios-sdk#45]
Is it possible to get 468 landmarks points array in the console using arcore-ios-sdk?
I read all documentation and try using all available classes, but was not able to get the proper method, class or solution which returns 468 face landmarks. 
Can you please clarify this?

**Comment by jrullman** [comment]
Do you mean just the points of the mesh? It is stated here (https://developers.google.com/ar/develop/java/augmented-faces/creating-assets) that there are 468 points in the mesh. On iOS, you can get the points using GARAugmentedFaceMesh.
