### ISSUE TITLE
AugmentedFacesExample camera failure; works in 1.25

### ISSUE THREAD

**Issue by cpsauer** [google-ar/arcore-ios-sdk#47]
Hey ARCore folks,

Friendly heads that there seems to be something wrong with the 1.26 AugmentedFacesExample. Frames never start landing, so it's just a stream of `In renderer, currentFrame is nil.` [Things work fine in 1.25.]

Thanks!
Chris
(ex-Daydreamer)

**Comment by jrullman** [comment]
Sorry about this. We have identified the issue and a fix will be in 1.27 (expected late September).
For now I recommend just using 1.25.
