### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by Bersaelor** [google-ar/arcore-ios-sdk#49]
Hey there, 

our iOS project uses `ARCore` for old iPhones that don't support ARKit.

Are there any plans to support the SPM (Swift Package Manager) ? We'd like to end the usage of Cocoapods and this project is the last one needing this legacy package manager.

**Comment by jrullman** [comment]
What are you using the SDK for, Augmented Faces? I think at this point there are very few phones left that support one but not the other.

ARCore 1.33 was released today, and it includes beta support for SPM. You can download the pod bundle ([here](https://dl.google.com/dl/cpdc/045cc481e27f9658/ARCore-1.33.0.tar.gz) for 1.33), unzip it and use it as a local Swift Package. Instructions are contained in the bundled README.

**Comment by 15kingben** [comment]
Starting from release 1.36.0, Swift Package Manager is officially supported. Please see the README for installation instructions.
