### ISSUE TITLE
Face mesh blender export issue for xcode

### ISSUE THREAD

**Issue by jitz102002RD** [google-ar/arcore-ios-sdk#51]
Can anyone please let me know how to export 3d model from blender to xcode. I have exported my custom 3d model ( glasses on face mesh ) in .dae format and then i converted into scn. But it doesn't seems to be in right co-ordination. i have double checked Y settings for scnassets. But still no luck. I have searched this small export setting on google for many days but have no luck. Any small help would be great.

**Comment by tenback** [comment]
You can use the Debug View Hierarchy in Xcode to debug this kind of things. Most of the time the position to the camera is wrong, too large object size, no object material etc.

**Comment by jitz102002RD** [comment]
Thanks @tenback. I checked it's blender issue only. If i convert canonical_face_mesh.fbx online to .dae. It just placed on my face perfectly. I tried many ways z-up, y-up and so on but nothing works perfectly. Anyone has appropriate setting to just export fbx to dae for iOS would be very helpful

**Comment by jrullman** [comment]
Closing this, as it's not really specific to the ARCore iOS SDK.
