### ISSUE TITLE
Swift Package Manger Support – GeoSpatial API

### ISSUE THREAD

**Issue by arthurschiller** [google-ar/arcore-ios-sdk#52]
Hello,

are there any plans to distribute this project via Swift Package Manager?
Specifically I want to utilise the GeoSpatial API within an existing ARKit-based app that already migrated away from CocoaPods over a year ago. We are also using Firebase via Swift Package Manger and as ARCore via CocoaPods lists Firebase as a dependency it would effectively build Firebase twice.
Would greatly appreciate a reply.

Best regards
Arthur

**Comment by maxxfrazer** [comment]
Skipping Swift Package Manager with an SDK of this size and reach is a bit silly. Is there a technical reason why?
There's also some extremely outdated practices in the examples.

Such a great piece of technology, but the SDK's developer experience needs some TLC.

**Comment by jrullman** [comment]
ARCore 1.33 has beta support for SPM - you can download the pod bundle ([here](https://dl.google.com/dl/cpdc/045cc481e27f9658/ARCore-1.33.0.tar.gz) for 1.33), unzip it and use it as a local Swift Package. Follow the instructions in the bundled README file.

**Comment by arthurschiller** [comment]
Amazing @jrullman! 🙏 Thanks a lot, will check it out!

**Comment by arthurschiller** [comment]
Hi @jrullman,

quick update: so far I wasn't able to get this working. I also created a barebones super simple project with the following steps:

- added local Swift Package from the unzipped folder 'ARCore-1.33.0'
- linked the binaries for 'ARCoreGeospatial', 'ARCoreBase' and 'ARCoreGARSession' to my target
- added linker flag '$(inherited) -ObjC'

It always shows me a linker error, telling my bitcode is missing. If I disable bitcode for the target I get even more errors.
Screenshots attached.
Tested with both Xcode 13 and 14, minimum deployment target iOS 15.4.
Anything obvious I might be missing?

Thanks a lot!


![settings](https://user-images.githubusercontent.com/3637723/186144891-47fedfe9-5ba5-4a49-88f5-7a5568c694de.jpg)
![bitcode_enabled](https://user-images.githubusercontent.com/3637723/186144901-f2315080-547d-47f8-b0de-cd1998682590.jpg)
![bitcode_disabled](https://user-images.githubusercontent.com/3637723/186144910-1e374187-ec39-4f1b-b5ef-3d3cab86b087.jpg)

**Comment by arthurschiller** [comment]
Ahh okay #2 did the trick but I think this definitely needs to be documented better. My projects are Swift only and to get this working I had to create an Objective-C bridging header where I added the `@import ARCore;` statement.
As I suppose most new projects nowadays would be Swift exclusive I think that's a crucial step for the documentation.
Thanks for the help and hints @jrullman!

**Comment by arthurschiller** [comment]
Nevermind, so it all builds fine but at runtime I get the following exception:

<img width="1253" alt="Screenshot 2022-08-24 at 14 41 04" src="https://user-images.githubusercontent.com/3637723/186421163-4848a4a3-31e8-4fbd-b920-324b0b127832.png">
<img width="1015" alt="Screenshot 2022-08-24 at 14 42 13" src="https://user-images.githubusercontent.com/3637723/186421182-ad81cd6c-0b74-42b4-9c38-2064bcbeff05.png">

Did you get it to run in a Swift-only project?
The previous version 1.32.0 ran fine via CocoaPods.

**Comment by jrullman** [comment]
The unrecognized selector issue happens when you don't have the linker flag "-ObjC", which prevents the linker from throwing away Objective-C categories.

For the import statement, I believe it can just be a regular `import` statement in Swift, which is equivalent to `@import` in Objective-C.

**Comment by arthurschiller** [comment]
Thanks, it's working now. Forgot the linker flag this time. Appreciate the patience!

**Comment by sinano1107** [comment]
Hi @jrullman 
Can you please tell me how to download the pod bundle?
I am looking for pod bundles for versions other than 1.33 (e.g. 1.34), but I don't know how to get them on my own.

**Comment by arthurschiller** [comment]
> Hi @jrullman
> Can you please tell me how to download the pod bundle?
> I am looking for pod bundles for versions other than 1.33 (e.g. 1.34), but I don't know how to get them on my own.

Hi, you can find the download link in the podspec: https://github.com/CocoaPods/Specs/blob/master/Specs/4/e/a/ARCore/1.34.0/ARCore.podspec.json

Podspec can be retrieved here: https://cocoapods.org/pods/ARCore (Right sidebar – »See Podspec«)

**Comment by jrullman** [comment]
Stay tuned ;)

**Comment by 15kingben** [comment]
Starting from release 1.36.0, Swift Package Manager is officially supported. Please see the README for installation instructions.
