### ISSUE TITLE
Apple Silicon support (EXCLUDED_ARCHS: arm64)

### ISSUE THREAD

**Issue by gyulavoros** [google-ar/arcore-ios-sdk#59]
The current Pod spec [requires the following configuration](https://github.com/CocoaPods/Specs/blob/master/Specs/4/e/a/ARCore/1.32.0/ARCore.podspec.json#L18): `EXCLUDED_ARCHS[sdk=iphonesimulator*]": "arm64`

If I remove the configuration, then I get the following error message:
`<PATH_TO_PROJECT>/ARCoreGARSession.framework/ARCoreGARSession(GARSession.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64`.

The problem with `EXCLUDED_ARCHS` present in the config is that on M1/M2 MacBooks, it causes a lot of trouble. The biggest issue is that we cannot execute test suites due to the following error:
```
The bundle “<TEST_SUITE>.xctest” couldn’t be loaded because it doesn’t contain a version for the current architecture. The bundle doesn’t contain a version for the current architecture. Try installing a universal version of the bundle.
...
<TEST_SUITE>.xctest/<TEST_SUITE>' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

Why is the exclusion of the `arm64` architecture for simulators necessary? I think the best solution would be to provide `xcframeworks` that contain all the necessary combinations of architectures for physical devices and simulators.

**Comment by jrullman** [comment]
EXCLUDED_ARCHS was there because we didn't have Apple Silicon support before, so there was no way to use it on a M1/M2 Mac.

ARCore 1.33 was just released, and it contains XCFramework binaries with the arm64 simulator architecture included.
