### ISSUE TITLE
[!] Unable to find a specification for `ARCore (~> 1.2.1)`

### ISSUE THREAD

**Issue by arunabhdas** [google-ar/arcore-ios-sdk#6]
My Podfile looks as follows 

`=> cat Podfile 
target '<redacted>'
platform :ios, '11.0'
pod 'ARCore', '~> 1.2.1'
pod 'Firebase/Core', '~> 4.11'
pod 'Firebase/Database', '~> 4.11'`

When I run pod install, I get the folllowing error : 

`==> pod install
Analyzing dependencies
[!] Unable to find a specification for `ARCore (~> 1.2.1)``

**Comment by sammcd** [comment]
Since 1.2.1 was released yesterday, it is possible that your local Cocaopods repo does not know about it yet.

Would you mind running `pod repo update` and then trying `pod install` again?

Thanks!

**Comment by sammcd** [comment]
Marking this as closed, but if you continue to have issues feel free to reopen.
