### ISSUE TITLE
Unknown type name 'GARSession'; 'GARFrame'

### ISSUE THREAD

**Issue by gbhall** [google-ar/arcore-ios-sdk#66]
For the 'GeospatialExample.xcworkspace', no matter what I do cannot build the project.

Using M1 Pro.

**Comment by sirily11** [comment]
Same issue with XCode. I solved this by creating a new project and migrating the old one. However, the error shows up again. Then I upgrade the XCode to 14.1 and the errors are gone.

**Comment by gbhall** [comment]
I solved this in a similar manner. Deleted the project. Copied the files again and reinstalled the pods. Miraculously worked. Suggest that for others to follow.
