### ISSUE TITLE
The ar camera won't turn on due to a firebase issue.

### ISSUE THREAD

**Issue by hina9** [google-ar/arcore-ios-sdk#67]
While using the arcore geospatial api service with ios
Due to the fix, the following error occurs when running again, and the camera does not turn on.

`The default Firebase app has not yet been configured. Add `FirebaseApp.configure()` to your application initialization. This can be done in in the App Delegate's application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI). Read more: https://goo.gl/ctyzm8.`

I have never used Firebase before, so I am using it as below in the pod file.

` # Pods for remoshot_forest
  pod 'AFNetworking', '~> 4.0'
  pod 'ORStackView', '~> 3.0.1'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 7.0'
  pod 'CoreGPX'
  pod 'ARCore/Geospatial', '~> 1.33.0'`

How do I resolve that error?

**Comment by jrullman** [comment]
Firebase has nothing to do with the camera. Did you start an ARKit session and get the camera permission?

I believe you can safely ignore the warning message "The default Firebase app has not yet been configured."
