### ISSUE TITLE
Run ARCore crashed (iOS 15.6.1 iPhone 12)

### ISSUE THREAD

**Issue by kobeli** [google-ar/arcore-ios-sdk#68]
Fatal Exception: NSRangeException
0  CoreFoundation                 0x99288 __exceptionPreprocess
1  libobjc.A.dylib                0x16744 objc_exception_throw
2  CoreFoundation                 0x1a4318 -[__NSCFString characterAtIndex:].cold.1
3  CoreFoundation                 0x3792c __NSDictionaryMutablePlaceholder
4  ARKitCore                      0x2ffa0 -[ARParentImageSensor start]
5  ARKitCore                      0x10f29c -[ARSession _startSensorsWithRequiredDataTypes:optionalDataTypes:]
6  ARKitCore                      0xce14 -[ARSession _updateSessionWithConfiguration:options:]
7  ARKitCore                      0x108ad0 __42-[ARSession runWithConfiguration:options:]_block_invoke
8  libdispatch.dylib              0x1e6c _dispatch_call_block_and_release
9  libdispatch.dylib              0x3a30 _dispatch_client_callout
10 libdispatch.dylib              0xb124 _dispatch_lane_serial_drain
11 libdispatch.dylib              0xbcb4 _dispatch_lane_invoke
12 libdispatch.dylib              0x16500 _dispatch_workloop_worker_thread
13 libsystem_pthread.dylib        0x10bc _pthread_wqthread
14 libsystem_pthread.dylib        0xe5c start_wqthread

**Comment by jrullman** [comment]
This appears to be a crash in ARKit, not ARCore.
