### ISSUE TITLE
No "Image Augmentation" for IOS ?

### ISSUE THREAD

**Issue by yashukla47** [google-ar/arcore-ios-sdk#71]
Hi, I see that 

For ios, nothing is mentioned about Image augmentation in the docs or the code.

I have these 3 questions.

Does Arcore support image augmentation in ios?
if not then is there any plan to support it in the future?

What is the best way right now to integrate image augmentation in ios with ARcore is there any other thing can be used side by side with ARcore to implement it on ios?

Thank you

**Comment by sinano1107** [comment]
How about using ARKit?
https://developer.apple.com/documentation/arkit/content_anchors/detecting_images_in_an_ar_experience

**Comment by jrullman** [comment]
The ARCore feature "Augmented Images" is only available on Android, as there is a similar feature already in ARKit.
Please refer to the ARCore [developer site](https://developers.google.com/ar/) for documentation on available features.
