### ISSUE TITLE
MacOS Support

### ISSUE THREAD

**Issue by peymanbateni** [google-ar/arcore-ios-sdk#73]
Dear ARCore team,

Thank you very much for the amazing work on the iOS SDK. I just wanted to check in to see if there are any plans for expanding support to Mac applications. It would be enormously useful. Is it possible to use the existing iOS binaries for standalone Mac apps?

Thanks,
Peyman

**Comment by jrullman** [comment]
What would be the use case for that? AR is currently only supported on mobile devices. For example see [here](https://developer.apple.com/documentation/arkit) about ARKit:

"This framework ignores calls from Mac apps built with Mac Catalyst."

**Comment by peymanbateni** [comment]
Well, there are certainly AR applications for the desktop too, especially around face processing and filters (such as for video-conferencing, games, etc.). I suspect that for AugmentedFaces, it may be relatively straightforward to expand support to Mac devices. Would it be possible to make this possible? Is there an underlying source code for ARCore public/open source? (If so, I'd be happy to do the modification myself).

**Comment by peymanbateni** [comment]
Hi there, any updates on this front? :)

**Comment by jrullman** [comment]
ARCore is not open source, and we don't have immediate plans to support MacOS builds.

**Comment by peymanbateni** [comment]
Thank you very much for your response!
