### ISSUE TITLE
how to stop or pause GARSession

### ISSUE THREAD

**Issue by arenas7307979** [google-ar/arcore-ios-sdk#75]
hii, 
I would like to create a switch that can be used to toggle the state of the GARSession in iOS app, 
either pausing or resuming it at any time. 
Do you have any examples or explanations on how to pause and resume the GARSession?

**Comment by jrullman** [comment]
GARSession does not currently have explicit `pause` and `resume` methods. You can simply pause and resume your underlying `ARSession`, so that frames stop being generated.
