### ISSUE TITLE
Host cloud anchor is not working with JWT Token in ARCore v1.30.0

### ISSUE THREAD

**Issue by deepakrhtsdev** [google-ar/arcore-ios-sdk#77]
I'm not able to host/resolve anchors using the signed JWT token. I'm using the v1.30.0 because it is working fine with API Key but higher version not working even with API Key with XCode 14.2 and iOS 16.0.3. 

I'm using:
1. aud: audience claim "https://arcorecloudanchor.googleapis.com/" for v1.30.0, as suggested by documentation link: https://developers.google.com/ar/develop/cloud-anchors/endpoint-changes, because i'm using ARCore Cloud Anchor API (Legacy)
2. uid: unique user id
3. iss: service account email
4. sub: service account email
after decoding JWT Token, getting like this:
        "iss": "arcore-service@project-name-33424.iam.gserviceaccount.com",
        "sub": "arcore-service@project-name-33424.iam.gserviceaccount.com",
        "iat": 1677843786,
        "exp": 1680435786,
        "aud": "https://arcorecloudanchor.googleapis.com/",
        "uid": "6387025debd89765ac79d8b4"

When I'm try to host anchor with self.gSession?.hostCloudAnchor(arAnchor, ttlDays: 210) then getting call in session(_ session: GARSession, didFailToHost anchor: GARAnchor) method, without any useful information.

Sharing GARSession Initialization:
         do {
                gSession = try GARSession.session()
                gSession!.setAuthToken(AuthToken.authToken)
                printObj("Google Session Initialization Done with token")
            } catch let error {
                printObj("Failed to init Google Session with message: " + error.localizedDescription)
            }
            gSession?.delegate = delegate
            gSession?.delegateQueue = DispatchQueue.main

Host anchor code
_ = try self.gSession?.hostCloudAnchor(arAnchor, ttlDays: 10)

At the time of initialisation not getting any error like authorisation error or anything.

I want to say again host working fine with API key, but my required to change with JWT token so that I can increase live time.

**Comment by jrullman** [comment]
Did you enable the ARCore API for your cloud project? That's probably why your API key isn't working with newer versions of ARCore. I would upgrade to the latest and enable the ARCore API.

**Comment by deepakrhtsdev** [comment]
@jrullman According to doc we need to enable both ARCore and ARCoreCloudAnchor when we use below v1.33.0, and both are enabled because I'm using v1.30.0.

host/retrieve are working fine with api key, only issue in case of JWT Token.

**Comment by deepakrhtsdev** [comment]
@jrullman, when updating my pod to v1.35.0, getting Error Domain=GARSession Code=-9 and same code working fine with v1.30.0 and GARSession with API Key

why I'm getting error after updating pod v1.35.0?

**Comment by jrullman** [comment]
I noticed that token lifetime was 30 days - signed JWTs are expected to have a lifetime of 1 hour. I would try that.

**Comment by deepakrhtsdev** [comment]
Thanks @jrullman
