### ISSUE TITLE
Getting - Error Domain=GARSession Code=-9 in v1.35.0

### ISSUE THREAD

**Issue by deepakrhtsdev** [google-ar/arcore-ios-sdk#78]
Getting - Error Domain=GARSession Code=-9 in v1.35.0 with api key and JWT token both, when installing v1.30.0 and lower then working fine with api key but not with JWT Token?

**Comment by jrullman** [comment]
Please refer to GARSessionError.h for error codes, and be sure to read other doc comments for the specific APIs you are using.

**Comment by deepakrhtsdev** [comment]
@jrullman, I found "GARSessionErrorCodeIllegalState | The operation could not be completed because the session is in the wrong state." in Doc, I'm getting this error with v1.35.0, but same code working fine with v1.30.0, and not mentioned any where in the updated version that what I should make change for updated version, if this is in knowledge, please let me know that what i should change for this error in cloud anchor!

Specifications:
ARCore
ARKit + RealityKit
XCode 14.2

**Comment by deepakrhtsdev** [comment]
Thank you @jrullman, it worked for me
