### ISSUE TITLE
GARSession flag not using arcore service 

### ISSUE THREAD

**Issue by arenas7307979** [google-ar/arcore-ios-sdk#79]
Is there a flag or setting in GARSession that can be used to maintain the operation of the ARKit (i.e., continue to derive pose and display anchors), but without invoking the Google Cloud Anchors service (ARCORE) for geolocation image matching?

**Comment by arenas7307979** [comment]
my goal is to continue tracking anchors and rendering through the local ARKit on the device, without relying on global position updates (ARCore services), once initialization is stable.

**Comment by jrullman** [comment]
I'm not understanding what you are using the ARCore SDK for. Can you explain more?
