### ISSUE TITLE
Can not initialise GARSession; returns NIL

### ISSUE THREAD

**Issue by richrdp** [google-ar/arcore-ios-sdk#8]
We want to integrate ARCore Cloud-Anchor in our own Project. We can not use Cocoa-Pods, 
so we extracted ARCore.framework and dependencies out of the Cocoa-Pod. 

First we tested Google ARCore iOS Example App, which works without any problems.

Now we tried to create a new XCode augmented reality project and added all necessary libraries and
frameworks from that ARCore-Example Project.

When trying to initialise a GARSession it just returns NIL, without any error.
No log output, no crash, no error message.

My initialisation looks like this:

`
NSError* __autoreleasing *error = nil;
`
`
GARSession* gSession = [GARSession sessionWithAPIKey:@"AAAAAAAAAAAAAAA" bundleIdentifier:nil error:error];
`

How can we initialise the session?
How can we debug this further, because we don't see any error message?

Here is a link to our simple ARSample application:
https://www.dropbox.com/s/2jmh48x9n3dp3rx/ARCoreTest.zip?dl=0

**Comment by sammcd** [comment]
Thanks for using ARCore, and for letting me know that you are not using Cocoapods in your project. It is very helpful for me to know how developers are using the framework, and this helps me know that instructions on how to use our framework outside of Cocoapods should be more of a priority.


The type of the error here is an `NSError**` not an `NSError*`. This means you must pass a pointer to the `NSError*`. Simply replace your method to look more like: 

```
GARSession* gSession = [GARSession sessionWithAPIKey:@"AAAAAAAAAAAAAAA" bundleIdentifier:nil error:&error];
```

And you should be able to read the error. Apple has more information on this here: https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/ErrorHandlingCocoa/CreateCustomizeNSError/CreateCustomizeNSError.html

Once you are able to see the error, feel free to let me know if it isn't intuitive.

**Comment by richrdp** [comment]
Thanks for your very fast reply!

The error contains an error code, but does not provide a readable message/userInfo:
`error	NSError *`
`domain: "GARSession" - code: 18446744073709551615	0x00000001c425e690`
`_userInfo	id	0x0	0x0000000000000000`

**Comment by sammcd** [comment]
I think you are getting error code -1, but it is being printed as an unsigned int and is underflowing.

If I had to guess I think you may not have the Resources bundle that is shipped with the Cocoapod. In our sample app this is packaged by the build phase called `Copy Pods Resources`. I think things should work if you include this resource bundle in your app.

If this isn't correct would you mind giving me the output of `NSLog(@"Error: %@", error.localizedDescription);`?

Thanks,

**Comment by sammcd** [comment]
I'm to close this issue due to inactivity. But feel free to reach out if I haven't resolved your issue or if there is anything else I can help with!
