### ISSUE TITLE
How to show feature points in AR Swift?

### ISSUE THREAD

**Issue by deepakrhtsdev** [google-ar/arcore-ios-sdk#81]
In My project, I have a requirement to show feature points in AR so that user can sure about scan accuracy around. as I have checked android ar demo have same as my requirement but in iOS Demo don't have, so can you, let me know how can show feature points in AR?
using:
1.  ARCore v1.36.0
2. Language: Swift

**Comment by jrullman** [comment]
See here: https://developer.apple.com/documentation/arkit/arframe/2887449-rawfeaturepoints?language=objc

This question is about ARKit, not ARCore. Please only open issues in this repo for questions related to ARCore.
