### ISSUE TITLE
Stuck at First Run

### ISSUE THREAD

**Issue by ghus86** [google-ar/arcore-ios-sdk#82]
Hi 

I am developing an app with the GeoSpatial Api it works well in android 
but in iOS in the first time I run the app it get stuck only displaying Initializing AR
if I close the app and run it again the app works well.

Already tried to give permission for location and camera before launching the scene with the geo spatial API

Using 
unity 2021.3.14
ar foundation 4.2.7
arcore for iOS 1.36 
added via swift package manager only works with this configuration set to the unity framework
https://developers.google.com/ar/develop/ios/enable-arcore/#use_swift_package_manager

Xcode 14.3
iOS 16.5

@jrullman any tip how to fix this issue ?

**Comment by ghus86** [comment]
It stops because its not sure if the GeoSpatialMode  is supported

var featureSupport = EarthManager.IsGeospatialModeSupported(GeospatialMode.Enabled);
            switch (featureSupport)
            {
                case FeatureSupported.Unknown:

**Comment by jrullman** [comment]
Swift Package Manager is currently only supported with using the native iOS SDK. If using the ARCore Extensions for AR Foundation in Unity, you need to use CocoaPods.

Please follower the developer guide for either [Unity ARF](https://developers.google.com/ar/develop/unity-arf/geospatial/developer-guide) or [iOS native](https://developers.google.com/ar/develop/ios/geospatial/developer-guide).

**Comment by jrullman** [comment]
Are you using a very old version? The latest should be good.
What error were you getting with CocoaPods?

**Comment by ghus86** [comment]
I was using 1.10 but updating to the latest helped with the CocoaPods issue

Regarding the first issue I mentioned if the GeoSpatial is Unknow reloading the scene helps.

Thanks for thhe help
