### ISSUE TITLE
Unable to free resolved cloud anchors

### ISSUE THREAD

**Issue by sergeiromanov** [google-ar/arcore-ios-sdk#87]
The session fails to resolve new cloud anchors after successfully resolved 40 anchors (official limit). I keep resolved anchors GARAnchor in an array and delete them `anchors[id] = nil` shortly after resolving. However this delete operation seems to have no effect. It looks like the anchors are still considered active and `resolveCloudAnchor` throws an exception (GARSession error -6.) which means resource exhausted.
What is the correct way to release previously resolved cloud anchors?

sdk version 1.38.0

**Comment by sergeiromanov** [comment]
My bad. Completely missed GARSession.remove(anchor) in the docs. All good now.

**Comment by YogeshBhattGWL** [comment]
Hi @sergeiromanov 
I am using persistent cloud anchors but I have a problem detecting Vertical Planes like Large buildings and I want to place an object on top of Building while scanning standing from street using iPhone 11 with iOS 16.5.

Do you think if there is nay other way...

**Comment by sergeiromanov** [comment]
> Hi @sergeiromanov I am using persistent cloud anchors but I have a problem detecting Vertical Planes like Large buildings and I want to place an object on top of the Building while scanning standing from the street using iPhone 11 with iOS 16.5.
> 
> Do you think there is any other way?

Vertical plane detection is not going to help. The end of the plane is not going to be the end of the building. The best thing you can do is to place your content at certain height above the anchor. But I doubt the anchor location will be accurate enough to achieve what you want

**Comment by YogeshBhattGWL** [comment]
@sergeiromanov Do you mean that The scanning won’t work precisely for large distances like Large Buildings?

Also, I think according to my need I need to go with Geospatial Creator. What do you think?

**Comment by sergeiromanov** [comment]
@YogeshBhattGWL even for short distances ( < 3m ) the detected surface will not exactly match the physical object. Larger distances ( > 5m ) - no chance. I never used Geospatial Creator but sounds like the right tool for your use case.
