### ISSUE TITLE
Streetscape geometry rendered way above the altitude 

### ISSUE THREAD

**Issue by rohanbhatia56** [google-ar/arcore-ios-sdk#88]
Hi I am trying to use ARCore SDK for iOS v1.38.0 on iPhone 7, software vesion 14.7.1  but I am facing the following issues 
1. Streetscape geometry is rendered way above the altitude of the phone. (Image attached)
2. Plane detection does not work when Streetscape geometry in visible, but works only when Streetscape geometry toggle in turned off. 
I want the streetscape geometry to be rendered at the correct altitude otherwise I am unable to place the anchors correctly.
![IMG_0002](https://github.com/google-ar/arcore-ios-sdk/assets/5320806/fa39d8af-5427-4ca9-b01f-8ab0fc073280)

Thanks

**Comment by rohanbhatia56** [comment]
Hi, any solution that I can do for this?

**Comment by YogeshBhattGWL** [comment]
@rohanbhatia56  Same happening with me in iPhone 11 with iOS 16.5

**Comment by 15kingben** [comment]
The accuracy of streetscape geometry is dependent on location, and may be less accurate in some areas depending on the age and quality of the StreetView imagery. However, the accuracy of Streetscape Geometry will be continuously improving so this may change in future, unrelated to ARCore updates.

2. This is the intended behavior of the [sample app](https://github.com/google-ar/arcore-ios-sdk/blob/ddf50a66cca516d3436e986a92370d3782271aee/Examples/GeospatialExample/GeospatialExample/ViewController.m#L1024) and [here](https://github.com/google-ar/arcore-ios-sdk/blob/ddf50a66cca516d3436e986a92370d3782271aee/Examples/GeospatialExample/GeospatialExample/ViewController.m#L774)
