### ISSUE TITLE
Thread 1: "+[GARDeviceProfile profileForIdentifier:osVersion:configurationManager:]: unrecognized selector sent to class 0x1052a7610"

### ISSUE THREAD

**Issue by ertembiyik** [google-ar/arcore-ios-sdk#90]
got an exception raised when launching application with the latest ARCore release added using SPM

the object under the 0x1052a7610 address is GARDeviceProfile

Requirements:
XCode: 14.3.1 
Device: iPhone 14 Pro (physical device)
OS: 16.5.1

**Comment by rbadoux** [comment]
Hi @ertembiyik, how did you manage to fix this issue ? I'm facing it right now and don't quite understand where this stems from. Thanks !

**Comment by ertembiyik** [comment]
> Hi @ertembiyik, how did you manage to fix this issue ? I'm facing it right now and don't quite understand where this stems from. Thanks !

hello, follow steps from the Readme, i remember i have missed the step with linking

**Comment by rbadoux** [comment]
Thank you for your quick reply ! 
I thought everything was in order but after redoing all the steps from the readme, the error disappeared. 
Thanks again !
