### ISSUE TITLE
VisionOS support

### ISSUE THREAD

**Issue by ertembiyik** [google-ar/arcore-ios-sdk#91]
VisionOS doesn't have ARFrame in its sdk (https://developer.apple.com/documentation/arkit/arframe), so for now there is no way to update GARSession on this platform using update method (https://developers.google.com/ar/reference/ios/interface/GARSession#update:error:)

Can you please add support to this platform? (using DataProviders data I assume)

**Comment by jrullman** [comment]
Unfortunately, the Vision Pro does not provide access to critical data streams, including camera images and GPS (see the [Compatibility checklist](https://developer.apple.com/visionos/compatibility-evaluations/), for example). For that reason, none of ARCore's features can be implemented on the device.
