### ISSUE TITLE
Rooftop Anchors seem to failing

### ISSUE THREAD

**Issue by raymondskl** [google-ar/arcore-ios-sdk#94]
Using the Geospatial Example, Rooftop Anchors are being spawned on the terrain.

**Comment by 15kingben** [comment]
Rooftop Anchors may appear on the terrain if:

1. There is no StreetScape Geometry building at that lat/long
2. The [quality](https://developers.google.com/ar/reference/ios/group/GARStreetscapeGeometryQuality) of the building at that lat/long is LOD_1, as these buildings may not have rooftops.
